Faith/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('base.urls')),
    path('clients/', include('client.urls')),
    path('jobs/', include('jobs.urls')),
    path('billing/', include('billing.urls')),
    path('reports/', include('reports.urls')),
    path('refund/', include('refund.urls')),


]

base/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    
    path('', views.home, name='home'),
    path('dashboard/', views.baseHome, name='dashboard'),
    path('headers/', views.HeaderFormView.as_view(), name='headers')
]

jobs/urls.py
from django.urls import path

from . import views

from .views import CreateView, JobCreateView, JobListView, PIDCreateView, PIDListView


urlpatterns = [ 
    path('create_job/', JobCreateView.as_view(), name='create_job'),
    path('job_list/', JobListView.as_view(), name='job_list'),
    path('edit_job/<str:pk>', views.editJob, name='edit_job'),
    path('sendmail/<str:pk>', views.sendMail, name='sendmail'),

    #PID URLS
    
    path('create_pid/', PIDCreateView.as_view(), name='create_pid'),
    path('edit_pid/<str:pk>', views.editPID, name='edit_pid'),
    path('pid_list/', PIDListView.as_view(), name='pid_list'),
]

jobs/models.py
from django.db import models

from client.models import Client
from base.models import Item, LOLO, ShippingLine, Terminal

# Create your models here.

class Job(models.Model):
    DUTYTYPE = (
        ('%', '%'),
        ('F', 'F')
    )
    jobNo = models.IntegerField(unique=True)
    jobDate = models.DateField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    containers = models.IntegerField(null=True, blank=True)
    size = models.IntegerField(null=True, blank=True)
    packages = models.CharField(max_length=200)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    description = models.CharField(max_length=250, null=True, blank=True)
    vessel = models.CharField(max_length=200)
    igm = models.IntegerField()
    igmDate = models.DateField()
    index = models.IntegerField()
    lc = models.CharField(max_length=200, null=True, blank=True)
    lcDate = models.DateField(null=True, blank=True)
    bl = models.CharField(max_length=200)
    blDate = models.DateField(null=True, blank=True)
    dv = models.FloatField()
    quantity = models.FloatField()

    exRate = models.FloatField()
    importValueUSD = models.FloatField()
    pkr = models.IntegerField()
    insurance = models.IntegerField(null=True, blank=True)
    landingCharges = models.IntegerField()
    importValue = models.IntegerField()
    dutyType = models.CharField(max_length=5, choices=DUTYTYPE, null=True, blank=True)
    rateOfDuty = models.FloatField(null=True, blank=True)
    customDuty = models.IntegerField(null=True, blank=True)
    rateOfAddDuty = models.FloatField(null=True, blank=True)
    addCustomDuty = models.IntegerField(null=True, blank=True)
    rateOfST = models.FloatField(null=True, blank=True)
    salesTax = models.IntegerField(null=True, blank=True)
    rateOfIT = models.FloatField(null=True, blank=True)
    incomeTax = models.IntegerField(null=True, blank=True)
    rateOfCess = models.FloatField(null=True, blank=True)
    cess = models.IntegerField(null=True, blank=True)
    rateOfRD = models.FloatField(null=True, blank=True)
    rd = models.IntegerField(null=True, blank=True)
    rateOfAD = models.FloatField(null=True, blank=True)
    antiDumping = models.IntegerField(null=True, blank=True)
    excise = models.IntegerField(null=True, blank=True)
    terminalCharges = models.IntegerField(null=True, blank=True)
    do = models.IntegerField(null=True, blank=True)
    deposit = models.IntegerField(null=True, blank=True)
    advanceRent = models.IntegerField(null=True, blank=True)
    loloCharges = models.IntegerField(null=True, blank=True)
    total = models.IntegerField()

    terminal = models.ForeignKey(Terminal, on_delete=models.CASCADE)
    shipping = models.ForeignKey(ShippingLine, on_delete=models.CASCADE)
    lolo = models.ForeignKey(LOLO, on_delete=models.CASCADE, null=True, blank=True)
    faithCheck = models.IntegerField(null=True, blank=True)
    psqcaSDC = models.IntegerField(null=True, blank=True)
    showSDC = models.BooleanField(default=False)
    psqcaTesting = models.IntegerField(null=True, blank=True)
    showTesting = models.BooleanField(default=True)

    billed = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.jobNo)


#PID
class PID(models.Model):
    DUTYTYPE = (
        ('%', '%'),
        ('F', 'F')
    )
    PIDNo = models.IntegerField(unique=True)
    Date = models.DateField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    containers = models.IntegerField(null=True, blank=True)
    size = models.IntegerField(null=True, blank=True)
    packages = models.CharField(max_length=200)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    description = models.CharField(max_length=250, null=True, blank=True)
    vessel = models.CharField(max_length=200)
    igm = models.IntegerField()
    igmDate = models.DateField()
    index = models.IntegerField()
    lc = models.CharField(max_length=200, null=True, blank=True)
    lcDate = models.DateField(null=True, blank=True)
    bl = models.CharField(max_length=200)
    blDate = models.DateField(null=True, blank=True)
    dv = models.FloatField()
    quantity = models.FloatField()

    exRate = models.FloatField()
    importValueUSD = models.FloatField()
    pkr = models.IntegerField()
    insurance = models.IntegerField(null=True, blank=True)
    landingCharges = models.IntegerField()
    importValue = models.IntegerField()
    dutyType = models.CharField(max_length=5, choices=DUTYTYPE, null=True, blank=True)
    rateOfDuty = models.FloatField(null=True, blank=True)
    customDuty = models.IntegerField(null=True, blank=True)
    rateOfAddDuty = models.FloatField(null=True, blank=True)
    addCustomDuty = models.IntegerField(null=True, blank=True)
    rateOfST = models.FloatField(null=True, blank=True)
    salesTax = models.IntegerField(null=True, blank=True)
    rateOfIT = models.FloatField(null=True, blank=True)
    incomeTax = models.IntegerField(null=True, blank=True)
    rateOfCess = models.FloatField(null=True, blank=True)
    cess = models.IntegerField(null=True, blank=True)
    rateOfRD = models.FloatField(null=True, blank=True)
    rd = models.IntegerField(null=True, blank=True)
    rateOfAD = models.FloatField(null=True, blank=True)
    antiDumping = models.IntegerField(null=True, blank=True)
    excise = models.IntegerField(null=True, blank=True)
    terminalCharges = models.IntegerField(null=True, blank=True)
    advanceRent = models.IntegerField(null=True, blank=True)
    do = models.IntegerField(null=True, blank=True)
    deposit = models.IntegerField(null=True, blank=True)
    loloCharges = models.IntegerField(null=True, blank=True)
    total = models.IntegerField()

    terminal = models.ForeignKey(Terminal, on_delete=models.CASCADE)
    shipping = models.ForeignKey(ShippingLine, on_delete=models.CASCADE)
    lolo = models.ForeignKey(LOLO, on_delete=models.CASCADE, null=True, blank=True)
    faithCheck = models.IntegerField(null=True, blank=True)
    psqcaSDC = models.IntegerField(null=True, blank=True)
    showSDC = models.BooleanField(default=True)
    psqcaTesting = models.IntegerField(null=True, blank=True)
    showTesting = models.BooleanField(default=True)

    billed = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.PIDNo)

jobs/forms.py
from django import forms
from django.forms import ModelForm
from .models import Job, PID


class DateInput(forms.DateInput):
    input_type = 'date'

class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
    

    
class PIDForm(ModelForm):
    class Meta:
        model = PID
        fields = '__all__'

jobs/views.py
import io
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from reports.utils import render_to_pdf

from django.http import HttpResponse

from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render, redirect
from .models import PID, Job
from .forms import JobForm, PIDForm
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from .filter import JobFilter, PIDFilter


# Create your views here.


#@login_required(login_url='login')
class JobCreateView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = Job
    form_class = JobForm
    template_name = 'jobs/create_job.html'
    success_url = reverse_lazy('job_list')

    def form_invalid(self, form: JobForm) -> HttpResponse:
        print(form.errors)
        return super().form_invalid(form)
    

@login_required(login_url='login')
def editJob(request, pk):
    job = Job.objects.get(id=pk)
    form = JobForm(instance=job)
    if request.method == 'POST':
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            return redirect('job_list')
    context = {
        'form': form,
    }
    return render(request, 'jobs/create_job.html', context)

#@login_required(login_url='login')
class JobListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Job
    template_name = "jobs/job_list.html"
    #context_object_name = 'jobs'
    ordering = ['-jobNo']
    paginate_by = 10
    paginate_orphans = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["jobFilter"] = JobFilter(self.request.GET, queryset=self.get_queryset()) 
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return JobFilter(self.request.GET, queryset=queryset).qs
    
    
def sendMail(request, pk):
    job = Job.objects.get(id=pk)

    if request.method == 'POST':
        emailTo = request.POST['emailTo']
        emailSubject = request.POST['emailSubject']
        #emailFile = request.POST['emailFile'] 
        emailMsg = request.POST ['emailMsg']
        fromEmail = settings.EMAIL_HOST_USER
        print(emailTo)

        send_mail(
            emailSubject,
            emailMsg,
            fromEmail,
            [emailTo,], 
            
            #emailFile,
        )
        #generate_obj_pdf(job.id)
        if send_mail:
            return redirect('job_list')
    context = {
        'job': job,
    }
    return render(request, 'jobs/email.html', context)

#XHTML 2 PDF

#FOR EMAIL
def generate_obj_pdf(instance_id):
     obj = Job.objects.get(id=instance_id)
     context = {'instance': obj}
     pdf = render_to_pdf('jobs/reports/calculationsheet.html', context)
     filename = "mytestpdf.pdf"
     #obj.save(filename, File(io.BytesIO(pdf.content)))


class JobsReportPDF(LoginRequiredMixin, View):
    login_url = 'login'
    def get(self, request, *args, **kwargs):
        startDate = request.GET['start-date']
        endDate = request.GET['end-date']
        jobs = Job.objects.filter(jobDate__range=[startDate, endDate]).order_by('jobNo')
        
        context = {
            'jobs': jobs,
            'startDate': startDate,
            'endDate': endDate,
        }
        pdf = render_to_pdf('jobs/reports/jobreport.html', context)
        return pdf


class PIDCreateView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = PID
    form_class = PIDForm
    template_name = 'jobs/create_pid.html'
    success_url = reverse_lazy('pid_list')

    def form_invalid(self, form: PIDForm) -> HttpResponse:
        print(form.errors)
        return super().form_invalid(form)

@login_required(login_url='login')
def editPID(request, pk):
    pid = PID.objects.get(id=pk)
    form = PIDForm(instance=pid)
    if request.method == 'POST':
        form = PIDForm(request.POST, instance=pid)
        if form.is_valid():
            form.save()
            return redirect('pid_list')
    context = {
        'form': form,
    }
    return render(request, 'jobs/create_pid.html', context)

#@login_required(login_url='login')
class PIDListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = PID
    template_name = "jobs/pid_list.html"
    #context_object_name = 'jobs'
    ordering = ['-PIDNo']
    paginate_by = 10
    paginate_orphans = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["pidFilter"] = PIDFilter(self.request.GET, queryset=self.get_queryset()) 
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return JobFilter(self.request.GET, queryset=queryset).qs

jobs/templates/jobs/create_job.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}Add New Job{% endblock title %}


{% block content %}
<style>
.alert {
  padding: 20px;
  background-color: #f44336;
  color: white;
}

.closebtn {
  margin-left: 15px;
  color: white;
  font-weight: bold;
  float: right;
  font-size: 22px;
  line-height: 20px;
  cursor: pointer;
  transition: 0.3s;
}

.closebtn:hover {
  color: black;
}
</style>
<br>
<div class="form-group">
  <form class="row g-3 form-inline" action="" method="POST">
    {% csrf_token %}
    <div class="col-md-12 text-center">
      <h1>Job Details</h1>
    </div>
    <div class="col-md-1">
      <label for="id_jobNo" class="form-label">Job No</label>
      {% render_field form.jobNo class="form-control"%}
        {{form.errors.jobNo}}
    </div>

    <div class="col-md-2">
      <label for="id_jobDate" class="form-label">Job Date</label>
      {% render_field form.jobDate|attr:"data-mask:00-00-0000" placeholder="dd-mm-yyyy" class="form-control date" %}
    </div>

    <div class="col-9">
      <label for="id_client" class="form-label">Client</label>
      {% render_field form.client class="form-control"%}
    </div>
    
    <div class="col-1">
      <label for="id_packages" class="form-label">Container(s)</label>
      {% render_field form.containers class="form-control"%}
    </div>
    
    <div class="col-1">
      <label for="id_packages" class="form-label">Size</label>
      {% render_field form.size class="form-control"%}
    </div>
    <div class="col-4">
      <label for="id_packages" class="form-label">Packages</label>
      {% render_field form.packages class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_item" class="form-label">Item</label>
      {% render_field form.item class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_item" class="form-label">Description</label>
      {% render_field form.description class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_vessel" class="form-label">Vessel</label>
      {% render_field form.vessel class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_igm" class="form-label">IGM #</label>
      {% render_field form.igm class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_igmDate" class="form-label">Date</label>
      {% render_field form.igmDate|attr:"data-mask:00-00-0000" placeholder="dd-mm-yyyy" class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_index" class="form-label">Index #</label>
      {% render_field form.index class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_lc" class="form-label">L/C</label>
      {% render_field form.lc class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_lcDate" class="form-label">Date</label>
      {% render_field form.lcDate|attr:"data-mask:00-00-0000" placeholder="dd-mm-yyyy" class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_bl" class="form-label">Bill of Lading</label>
      {% render_field form.bl class="form-control"%}
    </div>

    <div class="col-3">
      <label for="id_blDate" class="form-label">Date</label>
      {% render_field form.blDate|attr:"data-mask:00-00-0000" placeholder="dd-mm-yyyy" class="form-control"%}
    </div>

    <div class="text-center">
      <h1>Calculation</h1>
    </div>


    <div class="col-2">
      <label for="id_dv" class="form-label">Declare Value</label>
      {% render_field form.dv class="form-control"%}
    </div>

    <div class="col-2">
      <label for="id_quantity" class="form-label">Quantity</label>
      {% render_field form.quantity class="form-control"%}
    </div>

    <div class="col-2">
      <label for="id_importValue" class="form-label">Import Value $</label>
      {% render_field form.importValueUSD|attr:"readonly" class="form-control" %}
    </div>

    <div class="col-2">
      <label for="id_exRate" class="form-label">Exchange Rate</label>
      {% render_field form.exRate class="form-control"%}
    </div>

    <div class="col-4">
      <label for="id_pkr" class="form-label">Import Value (PKR)</label>
      {% render_field form.pkr|attr:"readonly" class="form-control"%}
    </div>

    <div class="col-sm-2">
      <label for="id_insurance" class="form-label">Insurance</label>
    </div>

    <div class="col-sm-2">
      {% render_field form.insurance class="form-control"%}
    </div>

    <div class="col-sm-1">
      <label for="" class="form-label lg"></label>
    </div>

    <div class="col-sm-2">
      <label for="" class="form-label">Custom Duty</label>
    </div>
    <div class="col-sm-1">
      {% render_field form.dutyType class="form-control"%}
    </div>
    <div class="col-sm-1">
      {% render_field form.rateOfDuty class="form-control"%}
    </div>
    <div class="col-sm-3">
      {% render_field form.customDuty|attr:"readonly" class="form-control"%}
    </div>

    <div class="col-sm-2">
      <label for="id_landingCharges" class="form-label">Landing Charges</label>
    </div>

    <div class="col-sm-2">
      {% render_field form.landingCharges|attr:"readonly" class="form-control"%}
    </div>

    <div class="col-sm-1">
      <label for="id_landingCharges" class="form-label"></label>
    </div>

    <div class="col-sm-2">
      <label for="id_landingCharges" class="form-label">Add Custom Duty</label>
    </div>

    <div class="col-sm-1">
      {% render_field form.rateOfAddDuty class="form-control"%}
    </div>
    <div class="col-sm-4">
      {% render_field form.addCustomDuty|attr:"readonly" class="form-control"%}
    </div>

    <div class="col-sm-2">
      <label for="id_landingCharges" class="form-label">Import Value</label>
    </div>

    <div class="col-sm-2">
      {% render_field form.importValue|attr:"readonly" class="form-control"%}
    </div>

    <div class="col-sm-1">
      <label class="form-label"></label>
    </div>

    <div class="col-sm-2">
      <label for="id_landingCharges" class="form-label">Sales Tax</label>
    </div>
    <div class="col-sm-1">
      {% render_field form.rateOfST class="form-control"%}
    </div>
    <div class="col-sm-4">
      {% render_field form.salesTax|attr:"readonly" class="form-control"%}
    </div>
    
    <div class="col-sm-2">
      <label for="id_landingCharges" class="form-label">Excise</label>
    </div>
    <div class="col-2">
      {% render_field form.excise class="form-control"%}
    </div>

    <div class="col-1">
      
    </div>
    <div class="col-sm-2">
      <label for="id_" class="form-label">Income Tax</label>
    </div>
    <div class="col-sm-1">
      {% render_field form.rateOfIT class="form-control"%}
    </div>
    <div class="col-sm-4">
      {% render_field form.incomeTax|attr:"readonly" class="form-control"%}
    </div>

    <div class="col-sm-5">
    </div>
    <div class="col-sm-2">
      <label for="" class="form-label">CESS</label>
    </div>
    <div class="col-sm-1">
      {% render_field form.rateOfCess class="form-control"%}
    </div>
    <div class="col-sm-4">
      {% render_field form.cess class="form-control"%}
    </div>
    
    <div class="col-sm-5">
    </div>
    <div class="col-sm-2">
      <label for="" class="form-label">RD</label>
    </div>
    <div class="col-sm-1">
      {% render_field form.rateOfRD class="form-control"%}
    </div>
    <div class="col-sm-4">
      {% render_field form.rd class="form-control"%}
    </div>
    
    <div class="col-sm-5">
    </div>
    <div class="col-sm-2">
      <label for="" class="form-label">Anti Dumping</label>
    </div>
    <div class="col-sm-1">
      {% render_field form.rateOfAD class="form-control"%}
    </div>
    <div class="col-sm-4">
      {% render_field form.antiDumping class="form-control"%}
    </div>



    <div class="col-sm-5">
    </div>
    <div class="col-sm-2">
    <label for="" class="form-label">Total</label>
    </div>

    <div class="col-sm-5">
      {% render_field form.total|attr:"readonly" class="form-control"%}
    </div>


    <div class="row mt-5">
      <div class="col-2">
        <label for="id_terminal" class="form-label">Terminal Wharfage</label>
        {% render_field form.terminalCharges class="form-control"%}
      </div>
  
      <div class="col-2">
        <label for="id_do" class="form-label">Delivery Order</label>
        {% render_field form.do class="form-control"%}
      </div>
  
      <div class="col-2">
        <label for="id_lolo" class="form-label">Container Deposit</label>
        {% render_field form.deposit class="form-control"%}
      </div>
  
      <div class="col-2">
        <label for="id_lolo" class="form-label">Advance Rent</label>
        {% render_field form.advanceRent class="form-control"%}
      </div>

      <div class="col-2">
        <label for="id_lolo" class="form-label">PSQC SDC</label>
        {% render_field form.psqcaSDC class="form-control text-end"%}
      </div>

      <div class="col-2">
        <label for="id_lolo" class="form-label">PSQC Testing</label>
        {% render_field form.psqcaSDC class="form-control text-end"%}
      </div>

    </div>

<div class="row mt-3">
  <div class="col-2">
    <label for="id_do" class="form-label">Terminal</label>
    {% render_field form.terminal class="form-control"%}
  </div>

  <div class="col-3">
    <label for="id_lolo" class="form-label">Shipping Line</label>
    {% render_field form.shipping class="form-control"%}
  </div>

  <div class="col-3">
    <label for="id_lolo" class="form-label">Shipping Line LOLO</label>
    {% render_field form.lolo class="form-control"%}
  </div>

  <div class="col-2">
    <label for="id_lolo" class="form-label">LOLO Charges</label>
    {% render_field form.loloCharges class="form-control"%}
  </div>

  <div class="col-2">
    <label for="" class="form-label">Faith Check</label>
    {% render_field form.faithCheck class="form-control"%}
  </div>
</div>


    <hr>
    <div class="d-flex justify-content-between">
      <input class="btn btn-primary btn-outline" type="submit" value="Save">
      <a href="" class="btn btn-danger btn-lg" type="">DELETE</a>
      <a href="" class="btn btn-warning btn-lg" type="">CLEAR</a>
      <a href="" class="btn btn-info btn-lg" type="">PRINT</a>
    </div>

  </form>

</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/dutycalculation.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>


{% endblock content %}

jobs/templates/jobs/email.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div>

        <div class="col-5">
            <label for="">To: {{job.client.person}}</label>
            <input name= "emailTo" class="form-control col-2" type="email" value="{{job.client.email}}">
        </div>
        <br>
        <div class="col-5">
            <label for="">Subject:</label>
            <input name= "emailSubject" class="form-control col-2" type="text" value="{{job.containers}}X{{job.size}} CONT {{job.item}} LC# {{job.lc}} Dated: {{job.lcDate}}">
        </div>
        <br>
        <div class="col-5">
            <label for="">File Attachment</label>
            <input name= "emailFile" class="form-control col-2" type="file" value="{{job.client.email}}">
        </div>
        <br>
        <div class="col-5">
            <label for="">Email Message:</label>
            <textarea name= "emailMsg" class="form-control" id="exampleFormControlTextarea1" rows="5" value="">Dear Sir, Please Find the Attach File</textarea>
        </div>
        <br>
    </div>
    <input class="btn btn-primary" type="submit" value="Submit">
</form>

{% endblock content %}

jobs/templates/jobs/job_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}Job Listing{% endblock title %}

{% block content %}

<!--Refund Modal-->

<div class="modal fade" id="refundModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Refund</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="" class="form-label">Job#</label>
            {% render_field itemform.name class="form-control" %}
          </div>

          <div class="mb-3">
            <label for="" class="form-label">HS.Code</label>
            {% render_field itemform.hscode class="form-control"%}
          </div>

          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </form>

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>




<!---->

<h1 class="text-center">Job Listing</h1>
<br>
<form class="" action="" method="get">

<center><div class="form-row"> 
            {{jobFilter.form}}
            <button class="btn btn-primary" type="submit">Search</button>
</div>
</center>
            
</form>

<br>
<table class="table table-striped align-middle" style="font-size: 13px;">
    <tr>
        <td colspan="9"><a class="btn btn-primary btn-lg d-grid gap-3 col-6 mx-auto"
                href="{% url 'create_job' %}">Create New Job</a></td>
    </tr>
    <tr>
        <th></th>
        <th>Job No</th>
        <th>Dated</th>
        <th>Client</th>
        <th>Description</th>
        <th>Packages</th>
        <th></th>
        <th></th>
    </tr>
    
    <tr>
        {% for j in object_list %}
        <td><a class="btn btn-info btn-sm" href="{% url 'edit_job' j.id %}">Edit</a></td>
        <td>{{j.jobNo}}</td>
        <td>{{j.jobDate|date:'d-m-Y'}}</td>
        <td>{{j.client}}</td>
        <td>{{j.item}}</td>
        {% if j.containers %}
            <td>{{j.containers}}X{{j.size}} CONT {{j.packages}}</td>
        {% else %}
            <td>{{j.packages}}</td>
        {% endif %}
    
        <td>
            <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-primary dropdown-toggle"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    Actions
                </button>
                <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                    <li><a class="dropdown-item" href="{% url 'calculationsheet' j.id %}">Print Calculation Sheet</a></li>
                    <li><a class="dropdown-item" href="{% url 'job_refund' j.id %}">Add Refund Info</a></li>
                    <li><a class="dropdown-item" href="{% url 'damagewaive' j.id %}">Damage Waive Letter</a></li>
                    <li><a class="dropdown-item" href="#">Something</a></li>
                    <li><a class="dropdown-item" href="#">Dropdown link</a></li>
                </ul>
            </div>
        </td>
        <td>
            <a class="btn btn-sm btn-info" href="{% url 'sendmail' j.id %}">E-Mail</a>
        </td>
    </tr>
    {% endfor %}
</table>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Previous</a>
        {% endif %}
        <span>{{ page_obj.number }}</span>

        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next</a>
        {% endif %}

    </span>
</div>


<script src="{% static 'js/jquery.js' %}"></script>
<script>
    //console.log("Hello World");
    //$("input").addClass("form-control");
    //$( "input" ).wrap( "<div class='col-md-2'></div>" );
    //$("select").addClass("form-control");
    //$("label").addClass("form-label");
</script>


{% endblock content %}